# Build React client
FROM node:20-alpine AS build
WORKDIR /app
COPY client-agri-map/package.json client-agri-map/package-lock.json ./
COPY client-agri-map/ .
RUN npm ci
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 4173
CMD ["nginx", "-g", "daemon off;"]
