# Generated by Django 6.0.6 on 2026-06-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperative',
            options={'ordering': ('-created_at',)},
        ),
    ]
