# Generated by Django 6.0.6 on 2026-06-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_cooperative_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperativemember',
            options={'ordering': ('joined_at',)},
        ),
    ]
