# Generated by Django 5.0.14 on 2026-06-23 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen_proxy', models.FloatField(blank=True, null=True)),
                ('moisture_index', models.FloatField(blank=True, null=True)),
                ('degradation_risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], default='low', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to='fields.field')),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
    ]
