# Generated by Django 6.0.6 on 2026-06-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='centroid_lat',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='centroid_lng',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
