# Generated by Django 6.0.6 on 2026-06-25 20:45

import fields.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_field_centroid_lat_field_centroid_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='geometry',
            field=models.JSONField(validators=[fields.models.validate_geojson]),
        ),
    ]
