# Generated by Django 6.1.1 on 2026-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fields", "0004_alter_field_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="crop_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="field",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
