# Generated by Django 5.0.14 on 2026-06-23 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_geojson', models.JSONField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_detections', to='fields.field')),
            ],
        ),
        migrations.CreateModel(
            name='CropPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_predictions', to='fields.field')),
            ],
            options={
                'ordering': ('-predicted_at',),
            },
        ),
        migrations.CreateModel(
            name='LandDegradation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('none', 'No Degradation'), ('low', 'Low'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degradation_records', to='fields.field')),
            ],
            options={
                'ordering': ('-detected_at',),
            },
        ),
        migrations.CreateModel(
            name='VegetationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('evi', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_indices', to='fields.field')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
