# Generated by Django 6.0.6 on 2026-06-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('fields', '0002_alter_field_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAreaPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_area_predictions', to='fields.field')),
            ],
            options={
                'ordering': ('-predicted_at',),
            },
        ),
        migrations.CreateModel(
            name='SoilPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_predictions', to='fields.field')),
            ],
            options={
                'ordering': ('-predicted_at',),
            },
        ),
    ]
