# Generated by Django 5.0.14 on 2026-06-23 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonSequestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_tons', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('methodology', models.CharField(choices=[('ndvi_based', 'NDVI-based estimation'), ('soil_organic_carbon', 'Soil Organic Carbon'), ('biomass_estimation', 'Biomass Estimation')], default='ndvi_based', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_records', to='fields.field')),
            ],
            options={
                'ordering': ('-calculated_at',),
            },
        ),
    ]
